version: "3.3"

services:
  server:
    container_name: kissanmarket_api
    restart: unless_stopped
    image: kissmarket-prod-1.0.0
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - kissmarket-shared

  frontend:
    container_name: kissanmarket_client
    restart: unless_stopped
    image: kissmarket-client-prod-1.0.0
    build:
      context: client/frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - kissmarket-shared
    depends_on:
      - server

networks:
  kissmarket-shared: