version: "3.3"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_PASSWORD=
    ports:
      - 3306:3306
    networks:
      - kissmarket-shared
    volumes:
      - ./mysql-db:/var/lib/mysql/data

  server:
    container_name: kissanmarket_api
    restart: unless_stopped
    image: kissmarket-prod-1.0.0
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - kissmarket-shared
    depends_on:
      - mysql

  frontend:
    container_name: kissanmarket_client
    restart: unless_stopped
    image: kissmarket-client-prod-1.0.0
    build:
      context: client/frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - kissmarket-shared
    depends_on:
      - server

networks:
  kissmarket-shared: