"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports =  {
  async up(queryInterface) {
    await queryInterface.bulkInsert("posts", [
      {
        title: "Kovakka",
        description: "Hello i want to sell kovakka",
        price: 50,
        quantity: 5,
        place: "Konni",
        latitude: 9.2267,
        longitude: 76.8497,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Pasuvin milk",
        description: "Hello i want to sell milk",
        price: 30,
        quantity: 3,
        place: "Konni",
        latitude: 9.2267,
        longitude: 76.8497,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Chakka",
        description: "Hello i want to sell Chakka",
        price: 80,
        quantity: 4,
        place: "Ayravon",
        latitude: 9.2225,
        longitude: 76.86,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Perakka",
        description: "Hello i want to sell guava",
        price: 120,
        quantity: 8,
        place: "Ayravon",
        latitude: 9.2225,
        longitude: 76.86,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Grapes",
        description: "Hello i want to sell grapes",
        price: 180,
        quantity: 7,
        place: "Attachakal",
        latitude: 9.2516,
        longitude: 76.8447,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Apples",
        description: "Hello i want to sell apples",
        price: 140,
        quantity: 2,
        place: "Attachakal",
        latitude: 9.2516,
        longitude: 76.8447,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Pavakka",
        description: "Hello i want to sell pavakka",
        price: 80,
        quantity: 9,
        place: "Perinjottackal",
        latitude: 9.2363,
        longitude: 76.8707,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "River Fish",
        description: "Hello i want to sell fish",
        price: 50,
        quantity: 5,
        place: "Perinjottackal",
        latitude: 9.2363,
        longitude: 76.8707,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Labrador Puppy",
        description: "Hello i want to sell dogs",
        price: 30,
        quantity: 3,
        place: "Pathanamthitta",
        latitude: 9.2363,
        longitude: 76.8707,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Cabbage",
        description: "Hello i want to sell cabbage",
        price: 80,
        quantity: 4,
        place: "Pathanamthitta",
        latitude: 9.2363,
        longitude: 76.8707,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Onion",
        description: "Hello i want to sell onion",
        price: 120,
        quantity: 8,
        place: "Ranni",
        latitude: 9.3866,
        longitude: 76.7856,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Clay pots",
        description: "Hello i want to sell clay pots",
        price: 180,
        quantity: 7,
        place: "Ranni",
        latitude: 9.3866,
        longitude: 76.7856,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Wild Honey",
        description: "Hello i want to sell wild honey",
        price: 140,
        quantity: 2,
        place: "Kumbazha",
        latitude: 9.2678,
        longitude: 76.8058,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Boiled Candy",
        description: "Hello i want to sell candy",
        price: 80,
        quantity: 9,
        place: "Kumbazha",
        latitude: 9.2678,
        longitude: 76.8058,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Persian Cats",
        description: "Hello i want to sell cats",
        price: 50,
        quantity: 5,
        place: "Thiruvalla",
        latitude: 9.3853,
        longitude: 76.575,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Goat Milk",
        description: "Hello i want to sell Goat Milk",
        price: 30,
        quantity: 3,
        place: "Thiruvalla",
        latitude: 9.3853,
        longitude: 76.575,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Nadan Kozhi",
        description: "Hello i want to sell Kozhi",
        price: 80,
        quantity: 4,
        place: "Kochi",
        latitude: 9.9312,
        longitude: 76.2673,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Alphonso Mango",
        description: "Hello i want to sell mango",
        price: 120,
        quantity: 8,
        place: "Kochi",
        latitude: 9.9312,
        longitude: 76.2673,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Coconut",
        description: "Hello i want to sell coconuts",
        price: 180,
        quantity: 7,
        place: "Thiruvananthapuram",
        latitude: 8.5241,
        longitude: 76.9366,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Peas",
        description: "Hello i want to sell peas",
        price: 140,
        quantity: 2,
        place: "Thiruvananthapuram",
        latitude: 8.5241,
        longitude: 76.9366,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Pineapples",
        description: "Hello i want to sell pineapples",
        price: 80,
        quantity: 9,
        place: "Kollam",
        latitude: 8.8932,
        longitude: 76.6141,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Wheat",
        description: "Hello i want to sell wheat",
        price: 80,
        quantity: 9,
        place: "Kollam",
        latitude: 8.8932,
        longitude: 76.6141,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Prawns",
        description: "Hello i want to sell prawns",
        price: 80,
        quantity: 9,
        place: "Kanjirapally",
        latitude: 9.5595,
        longitude: 76.7874,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Squid",
        description: "Hello i want to sell squid",
        price: 80,
        quantity: 9,
        place: "Kanjirapally",
        latitude: 9.5595,
        longitude: 76.7874,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Homemade Ink",
        description: "Hello i want to sell ink",
        price: 80,
        quantity: 9,
        place: "Karunagapally",
        latitude: 9.0598,
        longitude: 76.5356,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Handcrafted Baskets",
        description: "Hello i want to sell baskets",
        price: 80,
        quantity: 9,
        place: "Karunagapally",
        latitude: 9.0598,
        longitude: 76.5356,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Goldfish",
        description: "Hello i want to sell goldfish",
        price: 80,
        quantity: 9,
        place: "Mavelikkara",
        latitude: 9.2506,
        longitude: 76.5401,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Rose plants",
        description: "Hello i want to sell rose plants",
        price: 80,
        quantity: 9,
        place: "Mavelikkara",
        latitude: 9.2506,
        longitude: 76.5401,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Orchid plants",
        description: "Hello i want to sell orchids",
        price: 80,
        quantity: 9,
        place: "Vennikulam",
        latitude: 9.4061,
        longitude: 76.6682,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: "Orange",
        description: "Hello i want to sell oranges",
        price: 80,
        quantity: 9,
        place: "Vennikulam",
        latitude: 9.4061,
        longitude: 76.6682,
        home_delivery: true,
        views: 18,
        pincode: 680641,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },
  async down(queryInterface) {
    await queryInterface.bulkDelete("posts", null, {});
  },
};