/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
export async function seed(knex) {
  await knex('posts').del()
  await knex('posts').insert([
    {
      post_id: "post1",
      title: "Kovakka",
      description: "Hello i want to sell kovakka",
      price: 50,
      quantity: 5,
      place: "Konni",
      latitude: 9.2267,
      longitude: 76.8497,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post2",
      title: "Pasuvin milk",
      description: "Hello i want to sell milk",
      price: 30,
      quantity: 3,
      place: "Konni",
      latitude: 9.2267,
      longitude: 76.8497,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post3",
      title: "Chakka",
      description: "Hello i want to sell Chakka",
      price: 80,
      quantity: 4,
      place: "Ayravon",
      latitude: 9.2225,
      longitude: 76.86,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post4",
      title: "Perakka",
      description: "Hello i want to sell guava",
      price: 120,
      quantity: 8,
      place: "Ayravon",
      latitude: 9.2225,
      longitude: 76.86,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post5",
      title: "Grapes",
      description: "Hello i want to sell grapes",
      price: 180,
      quantity: 7,
      place: "Attachakal",
      latitude: 9.2516,
      longitude: 76.8447,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post6",
      title: "Apples",
      description: "Hello i want to sell apples",
      price: 140,
      quantity: 2,
      place: "Attachakal",
      latitude: 9.2516,
      longitude: 76.8447,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post7",
      title: "Pavakka",
      description: "Hello i want to sell pavakka",
      price: 80,
      quantity: 9,
      place: "Perinjottackal",
      latitude: 9.2363,
      longitude: 76.8707,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post8",
      title: "River Fish",
      description: "Hello i want to sell fish",
      price: 50,
      quantity: 5,
      place: "Perinjottackal",
      latitude: 9.2363,
      longitude: 76.8707,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post9",
      title: "Labrador Puppy",
      description: "Hello i want to sell dogs",
      price: 30,
      quantity: 3,
      place: "Pathanamthitta",
      latitude: 9.2363,
      longitude: 76.8707,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post10",
      title: "Cabbage",
      description: "Hello i want to sell cabbage",
      price: 80,
      quantity: 4,
      place: "Pathanamthitta",
      latitude: 9.2363,
      longitude: 76.8707,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post11",
      title: "Onion",
      description: "Hello i want to sell onion",
      price: 120,
      quantity: 8,
      place: "Ranni",
      latitude: 9.3866,
      longitude: 76.7856,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post12",
      title: "Clay pots",
      description: "Hello i want to sell clay pots",
      price: 180,
      quantity: 7,
      place: "Ranni",
      latitude: 9.3866,
      longitude: 76.7856,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post13",
      title: "Wild Honey",
      description: "Hello i want to sell wild honey",
      price: 140,
      quantity: 2,
      place: "Kumbazha",
      latitude: 9.2678,
      longitude: 76.8058,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post14",
      title: "Boiled Candy",
      description: "Hello i want to sell candy",
      price: 80,
      quantity: 9,
      place: "Kumbazha",
      latitude: 9.2678,
      longitude: 76.8058,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post15",
      title: "Persian Cats",
      description: "Hello i want to sell cats",
      price: 50,
      quantity: 5,
      place: "Thiruvalla",
      latitude: 9.3853,
      longitude: 76.575,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post16",
      title: "Goat Milk",
      description: "Hello i want to sell Goat Milk",
      price: 30,
      quantity: 3,
      place: "Thiruvalla",
      latitude: 9.3853,
      longitude: 76.575,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post17",
      title: "Nadan Kozhi",
      description: "Hello i want to sell Kozhi",
      price: 80,
      quantity: 4,
      place: "Kochi",
      latitude: 9.9312,
      longitude: 76.2673,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post18",
      title: "Alphonso Mango",
      description: "Hello i want to sell mango",
      price: 120,
      quantity: 8,
      place: "Kochi",
      latitude: 9.9312,
      longitude: 76.2673,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post19",
      title: "Coconut",
      description: "Hello i want to sell coconuts",
      price: 180,
      quantity: 7,
      place: "Thiruvananthapuram",
      latitude: 8.5241,
      longitude: 76.9366,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post20",
      title: "Peas",
      description: "Hello i want to sell peas",
      price: 140,
      quantity: 2,
      place: "Thiruvananthapuram",
      latitude: 8.5241,
      longitude: 76.9366,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post21",
      title: "Pineapples",
      description: "Hello i want to sell pineapples",
      price: 80,
      quantity: 9,
      place: "Kollam",
      latitude: 8.8932,
      longitude: 76.6141,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post22",
      title: "Wheat",
      description: "Hello i want to sell wheat",
      price: 80,
      quantity: 9,
      place: "Kollam",
      latitude: 8.8932,
      longitude: 76.6141,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post23",
      title: "Prawns",
      description: "Hello i want to sell prawns",
      price: 80,
      quantity: 9,
      place: "Kanjirapally",
      latitude: 9.5595,
      longitude: 76.7874,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post24",
      title: "Squid",
      description: "Hello i want to sell squid",
      price: 80,
      quantity: 9,
      place: "Kanjirapally",
      latitude: 9.5595,
      longitude: 76.7874,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post25",
      title: "Homemade Ink",
      description: "Hello i want to sell ink",
      price: 80,
      quantity: 9,
      place: "Karunagapally",
      latitude: 9.0598,
      longitude: 76.5356,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post26",
      title: "Handcrafted Baskets",
      description: "Hello i want to sell baskets",
      price: 80,
      quantity: 9,
      place: "Karunagapally",
      latitude: 9.0598,
      longitude: 76.5356,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post27",
      title: "Goldfish",
      description: "Hello i want to sell goldfish",
      price: 80,
      quantity: 9,
      place: "Mavelikkara",
      latitude: 9.2506,
      longitude: 76.5401,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post28",
      title: "Rose plants",
      description: "Hello i want to sell rose plants",
      price: 80,
      quantity: 9,
      place: "Mavelikkara",
      latitude: 9.2506,
      longitude: 76.5401,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post29",
      title: "Orchid plants",
      description: "Hello i want to sell orchids",
      price: 80,
      quantity: 9,
      place: "Vennikulam",
      latitude: 9.4061,
      longitude: 76.6682,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
    {
      post_id: "post30",
      title: "Orange",
      description: "Hello i want to sell oranges",
      price: 80,
      quantity: 9,
      place: "Vennikulam",
      latitude: 9.4061,
      longitude: 76.6682,
      home_delivery: true,
      views: 18,
      pincode: 680641,
    },
  ]);
}
